### ISSUE TITLE
Function collision with another plugin

### ISSUE THREAD

**Issue by brimby** [whoisjuan/craft-color-mixer#8]
The plugin called colorit has a function called hexToRgb too, and when I try to use the hexToRgb filter the colorit one is taking priority over the craft-color-mixer one. So I don't know if you could get together with the colorit dev and rename one of your functions or what. His function is less useful because it prints "rgb(0,0,0)" instead of just "0,0,0" so it can't be inserted into an rgba() without using the array.

You can view the colorit hexToRgb function [here](https://github.com/presseddigital/colorit/blob/master/src/helpers/ColorHelper.php)

**Comment by whoisjuan** [comment]
@brimby Changing the function name in Color Mixer or Colorit may not be viable since it automatically would break code for many people and I don't think there's is a low friction way to deprecate.

It seems that Colorit also gives access to their functions via utilities so for this particular situation, I would rely on their utilities `{{ craft.colorit.colours.hexToRgb(hex) }} `. 

Color Mixer relies exclusively on Twig filters so it doesn't have this alternative.
